% % objedinjeno 
function cloning()
fid = fopen('hmmdefs', 'w');
fprintf(fid,'%s\n',['~o<STREAMINFO> 1 39<VECSIZE> 39<NULLD><MFCC_0_D_A_Z><DIAGC>']);
fprintf(fid, '%s\n', ['~h "A"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "E"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "I"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "O"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "U"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "T"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "D"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "B"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "G"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "K"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "P"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "CC"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "CH"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "C"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "DZ"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "DJ"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "S"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "H"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "F"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "Z"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "M"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "N"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "NJ"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "V"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "ZH"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "SH"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "L"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "LJ"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "J"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "R"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "Y"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fprintf(fid, '%s', ['~h "sil"']);
fid1 = fopen('C:\htk\TOPGS\hmms\hmm00\proto1', 'r');
a=fread(fid1,'uint8=>char');
fprintf(fid,'%s',a);
fclose(fid);
end